exports.CHECK_MOBPSWD_AVAIL_SQL = "SELECT * FROM CONTROLLER WHERE MACADDRESS = ?";
exports.SET_CONTROLLER_SQL = "INSERT INTO CONTROLLER SET ?";
var controllerList = "SELECT CONTROLLERID as controllerID,CONTROLLERNAME as controllerName,CONTROLLERDATA as controllerData FROM CONTROLLER WHERE USERID = ?";
exports.GET_CONTROLLER_LIST = controllerList;

exports.UPDATE_CONTROLLER_LIVE_DATA = "UPDATE CONTROLLER SET CONTROLLERDATA = ? WHERE MACADDRESS = ? AND USERID = ?";

exports.GET_PRODUCT_ID = "SELECT CONTROLLERID as cID FROM CONTROLLER WHERE MACADDRESS = ? AND USERID = ?";

exports.SET_CONTROLLER_LIVE_DETAILS = "INSERT INTO CONTROLLERDETAILS SET ?";